# Server Configuration
server:
  port: 8080

# H2 Database Configuration
spring:
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password: CnB7aA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# Logging Configuration
logging:
  level:
    org.springframework.web: INFO
    com.origin.urlshortener: DEBUG 